### ISSUE TITLE
permissions  权限问题

### ISSUE THREAD

**Issue by QGB** [QGB/Android#9]
```
CLASSPATH=/data/app/me.zhanghai.android.beeshell-UxQtrDQlOM-Yb6I-yGUAaw==/base.apk /system/bin/app_process -Xrunjdwp:transport=dt_android_adb,suspend=n,server=y -Xcompiler-option --debuggable /system/bin --nice-name=me.zhanghai.android.beeshell:shell me.zhanghai.android.beeshell.ShellMain
```
APP AndroidManifest.xml 申请相应权限后执行 ，成功
root用户执行,成功！
```
~ # 
~ # 
~ # CLASSPATH=/data/app/me.zhanghai.android.beeshell-UxQtrDQlOM-Yb6I-yGUAaw==/base.apk /system/bin/app_process -Xrunjdwp:transport=dt_android_adb,suspend=n,server=y -Xcompiler-option --debuggable /system/bin --nice-name=me.zhanghai.android.beeshell:shell me.zhanghai.android.beeshell.ShellMain
|  Welcome to BeeShell 1.0.1
|  Powered by BeanShell 2.0b6
bsh> 
bsh> import android.bluetooth.BluetoothAdapter;BluetoothAdapter mBluetoothAdapter = BluetoothAdapter.getDefaultAdapter();  
$1 = null
bsh> mBluetoothAdapter.disable()
$2 = true
bsh> mBluetoothAdapter.enable()
$3 = true
bsh> mBluetoothAdapter.disable()
$4 = true
bsh> 
```
adb shell 执行，没有权限 ，失败！
```
bsh> mBluetoothAdapter.disable()
Sourced file: inline evaluation of: ``mBluetoothAdapter.disable();'' : Method Invocation mBluetoothAdapter.disable : at Line: 1 : in file: inline evaluation of: ``mBluetoothAdapter.disable();'' : mBluetoothAdapter .disable ( )

Target exception: java.lang.SecurityException: Need BLUETOOTH ADMIN permission: Neither user 2000 nor current process has android.permission.BLUETOOTH_ADMIN.

        at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:91)
        at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:96)
        at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:41)
        at bsh.Interpreter.eval(Interpreter.java:659)
        at bsh.Interpreter.eval(Interpreter.java:750)
        at bsh.Interpreter.eval(Interpreter.java:739)
        at me.zhanghai.android.beeshell.InteractiveInterpreter.execute(InteractiveInterpreter.kt:58)
        at me.zhanghai.android.beeshell.ShellMain.main(ShellMain.kt:76)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
Caused by: java.lang.SecurityException: Need BLUETOOTH ADMIN permission: Neither user 2000 nor current process has android.permission.BLUETOOTH_ADMIN.
        at android.os.Parcel.readException(Parcel.java:2013)
        at android.os.Parcel.readException(Parcel.java:1959)
        at android.bluetooth.IBluetoothManager$Stub$Proxy.disable(IBluetoothManager.java:356)
        at android.bluetooth.BluetoothAdapter.disable(BluetoothAdapter.java:976)
        at java.lang.reflect.Method.invoke(Native Method)
        at bsh.Reflect.invokeMethod(Reflect.java:131)
        at bsh.Reflect.invokeObjectMethod(Reflect.java:77)
        at bsh.Name.invokeMethod(Name.java:852)
        at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:69)
        ... 9 more

bsh>
bsh> import android.bluetooth.BluetoothAdapter;BluetoothAdapter mBluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
angler:/ $
angler:/ $ id
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc),3011(uhid) context=u:r:shell:s0
angler:/ $                                                                              
```

**Comment by QGB** [comment]
```
/data/app/me.zhanghai.android.beeshell-xhOf_-CdXm3oLhbY9pvgdQ==/lib # dumpsys package me.zhanghai.android.beeshell                                                                           
Activity Resolver Table:                                                                                                                                                                     
  Non-Data Actions:                                                                                                                                                                          
      android.intent.action.MAIN:                                                                                                                                                            
        db3cd55 me.zhanghai.android.beeshell/.ShellActivity filter a8133c2                                                                                                                   
          Action: "android.intent.action.MAIN"                                                                                                                                               
          Category: "android.intent.category.LAUNCHER"                                                                                                                                       
                                                                                                                                                                                             
Key Set Manager:                                                                                                                                                                             
  [me.zhanghai.android.beeshell]                                                                                                                                                             
      Signing KeySets: 51                                                                                                                                                                    
                                                                                                                                                                                             
Packages:                                                                                                                                                                                    
  Package [me.zhanghai.android.beeshell] (77a263a):                                                                                                                                          
    userId=10150                                                                                                                                                                             
    pkg=Package{18422eb me.zhanghai.android.beeshell}                                                                                                                                        
    codePath=/data/app/me.zhanghai.android.beeshell-UxQtrDQlOM-Yb6I-yGUAaw==                                                                                                                 
    resourcePath=/data/app/me.zhanghai.android.beeshell-UxQtrDQlOM-Yb6I-yGUAaw==                                                                                                             
    legacyNativeLibraryDir=/data/app/me.zhanghai.android.beeshell-UxQtrDQlOM-Yb6I-yGUAaw==/lib                                                                                               
    primaryCpuAbi=arm64-v8a                                                                                                                                                                  
    secondaryCpuAbi=null                                                                                                                                                                     
    versionCode=2 minSdk=21 targetSdk=30                                                                                                                                                     
    versionName=1.0.1                                                                                                                                                                        
    splits=[base]                                                                                                                                                                            
    apkSigningVersion=2                                                                                                                                                                      
    applicationInfo=ApplicationInfo{4a8a848 me.zhanghai.android.beeshell}                                                                                                                    
    flags=[ DEBUGGABLE HAS_CODE ALLOW_CLEAR_USER_DATA TEST_ONLY ALLOW_BACKUP ]                
    privateFlags=[ PRIVATE_FLAG_ACTIVITIES_RESIZE_MODE_RESIZEABLE_VIA_SDK_VERSION ]           
    dataDir=/data/user/0/me.zhanghai.android.beeshell                                         
    supportsScreens=[small, medium, large, xlarge, resizeable, anyDensity]                    
    timeStamp=2022-06-28 01:43:23              
    firstInstallTime=2022-06-28 01:43:43       
    lastUpdateTime=2022-06-28 01:43:43         
    signatures=PackageSignatures{ec5c6e1 [f313a37]}                                           
    installPermissionsFixed=true installStatus=1                                              
    pkgFlags=[ DEBUGGABLE HAS_CODE ALLOW_CLEAR_USER_DATA TEST_ONLY ALLOW_BACKUP ]             
    requested permissions:                     
      com.android.vending.BILLING              
      android.permission.USE_FULL_SCREEN_INTENT                                               
      android.permission.SCHEDULE_EXACT_ALARM  
      com.amazon.client.metrics.nexus.permission.CANCEL_SCHEDULED_UPLOAD                      

```
